name: Build

on: pull_request

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: do something
        run: |
          echo "step 1"
          echo "step 2"
