name: PR Check composite

on: 
  pull_request:
    paths:
      - 'custom-actions/composite/**'

jobs:
  composite-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-tests
        with:
          directory: custom-actions/composite
