name: PR Check docker

on: 
  pull_request:
    paths:
      - 'custom-actions/docker/**'

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-tests
        with:
          directory: custom-actions/docker
