name: PR Check simple

on: 
  pull_request:
    paths:
      - 'workflow/simple/**'

jobs:
  simple-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-tests
        with:
          directory: workflow/simple
